### PR TITLE
[Suggestion] Require character to be strong or tall to wield the hammer of justice

### PR DESCRIPTION
**Pull request by Cyrano7**
Makes it so you have to be an adult AND strong OR tall to wield the hammer of justice. Alternatively you could just have to be strong.

### CODE REVIEW

**Comment by tannerflick4** [comment]
@Vierwood  what do you think on this? I dont know enough about lore, but if I assume it was like Robert Baratheon's hammer, it was extremely heavy and unwieldy unless one had lots of strength. i would vote for making it strong or brawny, i.e, you could be tall but not strong.

**Comment by Cyrano7** [comment]
@tannerflick4 I don't think there is a brawny trait for the mod ATM. The description for that item say "...The colossal war hammer dwarfs all other weapons on the battlefield. Only a handful of men are strong enough to wield the hammer in battle...."

**Comment by tannerflick4** [comment]
Their is one with vanilla.

**Comment by Vierwood** [comment]
I believe the brawny trait requires one of the DLC, it's either Conclave or Reapers.

**Comment by tannerflick4** [comment]
Ok. Lets just go with strong then.

**Comment by blackninja9939** [comment]
You should pretty much never check directly for a congenital trait if the non inheritable version of it also exists. Instead use the appropriate scripted trigger which in this case is the is_strong_trigger = yes as it catches both the inheritable and non inheritable version (strong and brawny)
Brawny is also not DLC locked, we give it out in various events outside of just Conclave education.

**Comment by Cyrano7** [comment]
@blackninja9939 Okay i'll look into that when I get a chance. Thanks.

**Comment by tannerflick4** [comment]
@Cyrano7 I added that trigger to the artifact yesterday.

**Pull request merged**
